local M = {}

local function bg_or_none(color, transparent)
  if transparent then
    return "NONE"
  end
  return color
end

function M.build(c, opts)
  local transparent = opts.transparent
  local default_fg = c.fg_default or c.fg
  local normal_bg = bg_or_none(c.bg, transparent)
  local float_bg = bg_or_none(c.bg_float, transparent)
  local popup_bg = bg_or_none(c.bg_popup, transparent)
  local sidebar_bg = bg_or_none(c.bg_sidebar, transparent)
  local statusline_bg = bg_or_none(c.bg_statusline, transparent)
  local alt_bg = bg_or_none(c.bg_alt, transparent)

  return {
    Normal = { fg = default_fg, bg = normal_bg },
    NormalNC = { fg = default_fg, bg = normal_bg },
    NormalFloat = { fg = default_fg, bg = float_bg },
    FloatBorder = { fg = c.border, bg = float_bg },
    FloatTitle = { fg = c.accent, bg = float_bg, bold = true },
    ColorColumn = { bg = c.bg_subtle },
    CursorColumn = { bg = c.bg_cursorline },
    CursorLine = { bg = c.bg_cursorline },
    CursorLineNr = { fg = c.accent, bold = true },
    LineNr = { fg = c.fg_line_nr },
    SignColumn = { bg = normal_bg },
    VertSplit = { fg = c.border },
    WinSeparator = { fg = c.border },
    EndOfBuffer = { fg = c.bg_alt },
    FoldColumn = { fg = c.fg_muted, bg = alt_bg },
    Folded = { fg = c.fg_muted, bg = alt_bg },
    StatusLine = { fg = c.fg_ui, bg = statusline_bg },
    StatusLineNC = { fg = c.fg_muted, bg = statusline_bg },
    TabLine = { fg = c.fg_ui, bg = sidebar_bg },
    TabLineFill = { bg = sidebar_bg },
    TabLineSel = { fg = c.fg, bg = normal_bg, bold = true },
    Pmenu = { fg = c.fg, bg = popup_bg },
    PmenuSel = { fg = c.fg, bg = c.bg_subtle },
    PmenuSbar = { bg = c.bg_subtle },
    PmenuThumb = { bg = c.border },
    Visual = { bg = c.bg_visual },
    Search = { fg = c.fg, bg = c.bg_search },
    CurSearch = { fg = c.bg, bg = c.accent, bold = true },
    IncSearch = { fg = c.bg, bg = c.accent, bold = true },
    MatchParen = { fg = c.accent, bg = c.bg_cursorline, bold = true },
    Conceal = { fg = c.fg_muted },
    NonText = { fg = c.fg_muted },
    Whitespace = { fg = c.fg_muted },
    QuickFixLine = { bg = c.bg_subtle, bold = true },
    Directory = { fg = c.constant },
    Title = { fg = c.heading, bold = true },
    Underlined = { fg = c.link, underline = true },
    Question = { fg = c.info },
    MoreMsg = { fg = c.info },
    ModeMsg = { fg = c.accent },
    WarningMsg = { fg = c.warn },
    ErrorMsg = { fg = c.error },
    Error = { fg = c.error },
    Todo = { fg = c.heading, bold = true },
    Comment = { fg = c.fg_muted, italic = true },
    Constant = { fg = c.constant },
    String = { fg = c.string },
    Character = { fg = c.string },
    Number = { fg = c.number },
    Boolean = { fg = c.constant },
    Float = { fg = c.number },
    Identifier = { fg = c.fg_syntax },
    Function = { fg = c.func },
    Statement = { fg = c.keyword },
    Conditional = { fg = c.keyword },
    Repeat = { fg = c.keyword },
    Label = { fg = c.heading },
    Operator = { fg = c.keyword },
    Keyword = { fg = c.keyword },
    Exception = { fg = c.keyword },
    PreProc = { fg = c.keyword },
    Include = { fg = c.keyword },
    Define = { fg = c.keyword },
    Macro = { fg = c.keyword },
    PreCondit = { fg = c.keyword },
    Type = { fg = c.type },
    StorageClass = { fg = c.keyword },
    Structure = { fg = c.type },
    Typedef = { fg = c.type },
    Special = { fg = c.accent },
    SpecialChar = { fg = c.accent },
    Tag = { fg = c.tag },
    Delimiter = { fg = c.fg_punct },
    SpecialComment = { fg = c.fg_muted, italic = true },
    Debug = { fg = c.debug },
    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warn },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticSignError = { fg = c.error, bg = normal_bg },
    DiagnosticSignWarn = { fg = c.warn, bg = normal_bg },
    DiagnosticSignInfo = { fg = c.info, bg = normal_bg },
    DiagnosticSignHint = { fg = c.hint, bg = normal_bg },
    DiagnosticVirtualTextError = { fg = c.error, bg = c.bg_subtle },
    DiagnosticVirtualTextWarn = { fg = c.warn, bg = c.bg_subtle },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.bg_subtle },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = c.bg_subtle },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warn },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { bg = c.diff_delete },
    DiffText = { fg = c.fg, bg = c.bg_cursorline, bold = true },
    diffAdded = { fg = c.string },
    diffChanged = { fg = c.warn },
    diffRemoved = { fg = c.error },
    GitSignsAdd = { fg = c.string },
    GitSignsChange = { fg = c.warn },
    GitSignsDelete = { fg = c.error },
    ["@annotation"] = { fg = c.constant },
    ["@attribute"] = { fg = c.constant },
    ["@attribute.builtin"] = { fg = c.constant },
    ["@boolean"] = { fg = c.constant },
    ["@character"] = { fg = c.string },
    ["@character.special"] = { fg = c.accent },
    ["@comment"] = { fg = c.fg_muted, italic = true },
    ["@comment.documentation"] = { fg = c.fg_muted, italic = true },
    ["@comment.error"] = { fg = c.error, bold = true },
    ["@comment.todo"] = { fg = c.heading, bold = true },
    ["@comment.warning"] = { fg = c.warn, bold = true },
    ["@constant"] = { fg = c.constant },
    ["@constant.builtin"] = { fg = c.constant },
    ["@constant.macro"] = { fg = c.keyword },
    ["@constructor"] = { fg = c.func },
    ["@diff.delta"] = { fg = c.warn },
    ["@diff.minus"] = { fg = c.error },
    ["@diff.plus"] = { fg = c.string },
    ["@function"] = { fg = c.func },
    ["@function.builtin"] = { fg = c.func },
    ["@function.call"] = { fg = c.func },
    ["@function.macro"] = { fg = c.keyword },
    ["@function.method"] = { fg = c.func },
    ["@function.method.call"] = { fg = c.func },
    ["@keyword"] = { fg = c.keyword },
    ["@keyword.conditional"] = { fg = c.keyword },
    ["@keyword.conditional.ternary"] = { fg = c.keyword },
    ["@keyword.debug"] = { fg = c.debug },
    ["@keyword.directive"] = { fg = c.keyword },
    ["@keyword.directive.define"] = { fg = c.keyword },
    ["@keyword.exception"] = { fg = c.keyword },
    ["@keyword.function"] = { fg = c.keyword },
    ["@keyword.import"] = { fg = c.keyword },
    ["@keyword.modifier"] = { fg = c.keyword },
    ["@keyword.operator"] = { fg = c.keyword },
    ["@keyword.repeat"] = { fg = c.keyword },
    ["@keyword.return"] = { fg = c.keyword },
    ["@keyword.type"] = { fg = c.keyword },
    ["@label"] = { fg = c.heading },
    ["@markup"] = { fg = default_fg },
    ["@markup.heading"] = { fg = c.heading, bold = true },
    ["@markup.heading.1"] = { fg = c.heading, bold = true },
    ["@markup.heading.2"] = { fg = c.heading, bold = true },
    ["@markup.heading.3"] = { fg = c.heading, bold = true },
    ["@markup.heading.4"] = { fg = c.heading, bold = true },
    ["@markup.heading.5"] = { fg = c.heading, bold = true },
    ["@markup.heading.6"] = { fg = c.heading, bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.link, underline = true },
    ["@markup.link.label"] = { fg = c.markdown_link_text },
    ["@markup.link.url"] = { fg = c.link, underline = true },
    ["@markup.list"] = { fg = c.heading },
    ["@markup.list.checked"] = { fg = c.string },
    ["@markup.list.unchecked"] = { fg = c.fg_muted },
    ["@markup.math"] = { fg = c.constant },
    ["@markup.quote"] = { fg = c.fg_muted, italic = true },
    ["@markup.raw"] = { fg = c.fg_alt },
    ["@markup.raw.block"] = { fg = c.fg_alt },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { fg = c.heading, bold = true },
    ["@markup.underline"] = { underline = true },
    ["@module"] = { fg = c.type },
    ["@module.builtin"] = { fg = c.type },
    ["@number"] = { fg = c.number },
    ["@number.float"] = { fg = c.number },
    ["@operator"] = { fg = c.keyword },
    ["@property"] = { fg = c.constant },
    ["@punctuation.bracket"] = { fg = c.fg_punct },
    ["@punctuation.delimiter"] = { fg = c.fg_punct },
    ["@punctuation.special"] = { fg = c.fg_punct },
    ["@string"] = { fg = c.string },
    ["@string.documentation"] = { fg = c.fg_alt },
    ["@string.escape"] = { fg = c.accent },
    ["@string.regexp"] = { fg = c.string },
    ["@string.special"] = { fg = c.constant },
    ["@string.special.path"] = { fg = c.constant },
    ["@string.special.symbol"] = { fg = c.constant },
    ["@string.special.url"] = { fg = c.link, underline = true },
    ["@tag"] = { fg = c.tag },
    ["@tag.attribute"] = { fg = c.constant },
    ["@tag.delimiter"] = { fg = c.fg_punct },
    ["@type"] = { fg = c.type },
    ["@type.builtin"] = { fg = c.type },
    ["@type.definition"] = { fg = c.type },
    ["@variable"] = { fg = c.fg_syntax },
    ["@variable.builtin"] = { fg = c.constant },
    ["@variable.member"] = { fg = c.constant },
    ["@variable.parameter"] = { fg = c.parameter },
    ["@lsp.type.boolean"] = { link = "@boolean" },
    ["@lsp.type.builtinType"] = { link = "@type.builtin" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.escapeSequence"] = { link = "@string.escape" },
    ["@lsp.type.event"] = { link = "@type" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.modifier"] = { link = "@keyword.modifier" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.number"] = { link = "@number" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.regexp"] = { link = "@string.regexp" },
    ["@lsp.type.string"] = { link = "@string" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
    TSAnnotation = { link = "@annotation" },
    TSAttribute = { link = "@attribute" },
    TSBoolean = { link = "@boolean" },
    TSCharacter = { link = "@character" },
    TSComment = { link = "@comment" },
    TSConditional = { link = "@keyword.conditional" },
    TSConstant = { link = "@constant" },
    TSConstBuiltin = { link = "@constant.builtin" },
    TSConstMacro = { link = "@constant.macro" },
    TSConstructor = { link = "@constructor" },
    TSError = { link = "@comment.error" },
    TSException = { link = "@keyword.exception" },
    TSField = { link = "@property" },
    TSFloat = { link = "@number.float" },
    TSFunction = { link = "@function" },
    TSFuncBuiltin = { link = "@function.builtin" },
    TSFuncMacro = { link = "@function.macro" },
    TSInclude = { link = "@keyword.import" },
    TSKeyword = { link = "@keyword" },
    TSKeywordFunction = { link = "@keyword.function" },
    TSKeywordOperator = { link = "@keyword.operator" },
    TSLabel = { link = "@label" },
    TSMethod = { link = "@function.method" },
    TSNamespace = { link = "@module" },
    TSNumber = { link = "@number" },
    TSOperator = { link = "@operator" },
    TSParameter = { link = "@variable.parameter" },
    TSProperty = { link = "@property" },
    TSPunctDelimiter = { link = "@punctuation.delimiter" },
    TSPunctBracket = { link = "@punctuation.bracket" },
    TSPunctSpecial = { link = "@punctuation.special" },
    TSRepeat = { link = "@keyword.repeat" },
    TSString = { link = "@string" },
    TSStringEscape = { link = "@string.escape" },
    TSStringRegex = { link = "@string.regexp" },
    TSStrong = { link = "@markup.strong" },
    TSTag = { link = "@tag" },
    TSTagDelimiter = { link = "@tag.delimiter" },
    TSText = { link = "Normal" },
    TSTitle = { link = "@markup.heading" },
    TSType = { link = "@type" },
    TSTypeBuiltin = { link = "@type.builtin" },
    TSURI = { link = "@markup.link.url" },
    TSVariable = { link = "@variable" },
    TSVariableBuiltin = { link = "@variable.builtin" },
    markdownText = { fg = default_fg },
    markdownBold = { fg = c.heading, bold = true },
    markdownItalic = { italic = true },
    markdownH1 = { fg = c.heading, bold = true },
    markdownH2 = { fg = c.heading, bold = true },
    markdownH3 = { fg = c.heading, bold = true },
    markdownH4 = { fg = c.heading, bold = true },
    markdownH5 = { fg = c.heading, bold = true },
    markdownH6 = { fg = c.heading, bold = true },
    markdownHeadingDelimiter = { fg = c.heading, bold = true },
    markdownCode = { fg = c.fg_alt },
    markdownCodeBlock = { fg = c.fg_alt },
    markdownCodeDelimiter = { fg = c.markdown_link_text },
    markdownUrl = { fg = c.link, underline = true },
    markdownLinkText = { fg = c.markdown_link_text },
    markdownLinkDelimiter = { fg = c.markdown_bracket },
    markdownLinkTextDelimiter = { fg = c.markdown_bracket },
    markdownListMarker = { fg = c.heading },
    markdownOrderedListMarker = { fg = c.heading },
    markdownRule = { fg = c.fg_muted },
  }
end

return M
